name = "Ace Documentation (Fork)"
license = "MIT"
licenselink = "https://github.com/jijeeshhomelab/ace-documentation/blob/main/LICENSE"
description = "Fork of Ace Documentation theme used for internal and personal documentation sites."
homepage = "https://github.com/jijeeshhomelab/ace-documentation"
tags = ["documentation", "bootstrap", "responsive", "syntax highlighting", "docs"]
features = ["documentation", "bootstrap", "sass"]
min_version = "0.51.0"

[author]
  name = "Original: Vantage Design â€¢ Fork: Jijeesh"
  homepage = "https://github.com/jijeeshhomelab"
