name: ðŸ“– Deploy GitHub Pages Using Hugo

on:
  workflow_dispatch:
  push:
    branches:
      - "develop"
      - "DHC-[0-9].[0-9]"
      - "DHC-[0-9].[0-9]-latest"
      - "master-[2-9].[0-9]"

jobs:
  create-pages:
    uses: jijeeshhomelab/Actions/.github/workflows/hugo-pages.yml@main
    with:
      GH_BRANCH: ${{ github.ref_name }}
      # BASE_URL: "https://jijeeshhomelab.github.io/aec-documentation/"  # optional override
    secrets:
      GH_ACTIONS_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
