name: ðŸ§ª Test GitHub Pages Build

on:
  workflow_dispatch:
  pull_request:

jobs:
  test-build:
    uses: jijeeshhomelab/Actions/.github/workflows/test-build-pages.yml@main
    secrets:
      GH_ACTIONS_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
